### ISSUE TITLE
use torii from ember-adopted-addons

### ISSUE THREAD

**Issue by nvdk** [lblod/ember-acmidm-login#13]
Adding this is here so we don't lose track of it: https://github.com/adopted-ember-addons/torii

**Comment by nvdk** [comment]
this may no longer be relevant if we move forward with #14

**Comment by Windvis** [comment]
This is no longer needed after the [v2 release](https://github.com/lblod/ember-acmidm-login/releases/tag/v2.0.0) 👍.
